version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
      - redis
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  redis-data:
  static-data: