# Generated by Django 5.1 on 2024-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_enrollment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "session"), name="unique_user_session"
            ),
        ),
    ]
