# Generated by Django 5.1 on 2024-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_enrollment_unique_user_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="techniques",
            field=models.ManyToManyField(
                related_name="sessions", to="core.technique"
            ),
        ),
    ]
