# Generated by Django 5.1 on 2024-09-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_technique_meditationsession_techniques"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
