# Generated by Django 5.1 on 2024-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
