# Generated by Django 5.1 on 2024-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=120.5, max_digits=10
            ),
        ),
    ]
