---
name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check environment variables
        run: docker compose run --rm app sh -c "env"

      - name: Checkout
        uses: actions/checkout@v3

      - name: List files for debugging
        run: docker compose run --rm app sh -c "ls -R /app"

      - name: Test
        run: |
          docker compose run --rm app sh -c "
            python manage.py wait_for_db && 
            python manage.py test
          "

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

      - name: Format Check
        run: docker compose run --rm app sh -c "black --check ."
