name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files for debugging
        run: docker compose run --rm app sh -c "ls -R /app"

      - name: Test
        run: |
          docker compose run --rm app sh -c "
            python manage.py wait_for_db && 
            python manage.py test
          "

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

      - name: Format Check
        run: docker compose run --rm app sh -c "black --check ."
