---
name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          touch app/.env
          echo DB_HOST=${{ secrets.DB_HOST }} >> app/.env
          echo DB_NAME=${{ secrets.DB_NAME }} >> app/.env
          echo DB_USER=${{ secrets.DB_USER }} >> app/.env
          echo DB_PASS=${{ secrets.DB_PASS }} >> app/.env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> app/.env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> app/.env

      - name: Test
        run: |
          docker compose run --rm app sh -c "
            python manage.py wait_for_db &&
            python manage.py test
          "

      - name: Format Check
        run: docker compose run --rm app sh -c "black --check ."

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
