---
name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Compose environment
        run: |
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASS=${{ secrets.DB_PASS }}
          export REDIS_HOST=${{ secrets.REDIS_HOST }}
          export REDIS_PORT=${{ secrets.REDIS_PORT }}
          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          
          docker compose up -d db redis
          sleep 10 

      - name: List files for debugging
        run: docker compose run --rm app sh -c "ls -R /app"

      - name: Test
        run: |
          docker compose run --rm app sh -c "
            python manage.py wait_for_db &&
            python manage.py test
          "

      - name: Format Check
        run: docker compose run --rm app sh -c "black --check ."

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
