---
name: Checks

on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Docker Compose Plugin
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
      - name: Format Check
        run: docker compose run --rm app sh -c "black --check ."